add_newline = false

[username]
show_always = true
disabled = false
format = "[$user on ]($style)"
style_user = "202"

[hostname]
ssh_only = false
disabled = false
format = "[$hostname in ]($style)"
style = "yellow"

[directory]
style = "green"
truncation_length = 1

[git_branch]
style = "93"

[git_status]
style = "blue"

[line_break]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
time_format = "%a %b %d, %T"
style = "cyan"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[cmd_duration]
disabled = true
