if [ -f ~/.sh_path ]; then
	. ~/.sh_path
fi

if [ -f ~/.sh_profile ]; then
	. ~/.sh_profile
fi

#File containing all the aliases
if [ -f ~/.sh_aliases ]; then
	. ~/.sh_aliases
fi

#File customizing the prompt
#if [ -f ~/.sh_prompt ]; then
#	. ~/.sh_prompt
#fi
