export PATH="/usr/local/sbin:$PATH"

if [ -f ~/.bash_path ]; then
    . ~/.bash_path
fi

#Link to Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi
#if [ -f $(brew --prefix)/etc/bash_completion.d/git-completion.bash ]; then
#    . $(brew --prefix)/etc/bash_completion.d/git-completion.bash
#fi
#if [ -f `brew --prefix`/etc/bash_completion.d/git-flow-completion.bash ]; then
#    . `brew --prefix`/etc/bash_completion.d/git-flow-completion.bash
#fi

#File containing all the aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

#File customizing the prompt
if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
fi

#Exercism CLI completion
if [ -f ~/.config/exercism/exercism_completion.bash ]; then
  . ~/.config/exercism/exercism_completion.bash
fi
