export PATH="/usr/local/sbin:$PATH"

if [ -f ~/.bash_path ]; then
    . ~/.bash_path
fi

#Link to Bash completion
#if [ -f $(brew --prefix)/etc/bash_completion ]; then
#	. $(brew --prefix)/etc/bash_completion
#fi
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

#File containing all the aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

#File customizing the prompt
if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
fi
